#!/usr/bin/env bash
# Regenerate index.yaml — the catalog, DERIVED from each entry's package.yaml.
# Everything is a package self-fact; the catalog adds only verification status
# (computed by CI, since a package can't self-assert "I pass the current spec").
# interface/pins come from schema.yaml (#1468); capability surface is derived from
# tools.yaml/agents. Run from the repo root: scripts/build-index.sh
set -euo pipefail
cd "$(dirname "$0")/.."

python3 - <<'PY'
import glob, os, sys
try:
    import yaml
except ImportError:
    sys.exit("build-index needs PyYAML: pip install pyyaml")

def load(p):
    with open(p) as f:
        return yaml.safe_load(f) or {}

entries = []
for meta in sorted(glob.glob("templates/*/package.yaml") + glob.glob("patterns/*/package.yaml")):
    d = os.path.dirname(meta)
    m = load(meta)
    entries.append({
        "path": d,
        "tier": d.split("/")[0].rstrip("s"),   # template | pattern, from directory
        "name": m.get("name"),
        "version": m.get("version"),
        "description": (m.get("description") or "").strip() or None,
        "category": m.get("category"),
        "keywords": m.get("keywords"),
        "platform_version": m.get("platform_version"),
        # verification: populated by CI (verify + scenarios against current spec)
        "verification": None,
    })

out = {"version": 1, "entries": entries or []}
with open("index.yaml", "w") as f:
    f.write("# GENERATED by scripts/build-index.sh — do not edit by hand.\n")
    f.write("# Catalog derived from each entry's package.yaml. `verification` is filled by CI.\n")
    yaml.safe_dump(out, f, sort_keys=False, default_flow_style=False)
print(f"wrote index.yaml ({len(entries)} entries)")
PY
