#!/usr/bin/env bash
# Regenerate index.yaml — the catalog, DERIVED from each entry's package.yaml.
# No Colony-specific metadata file: name/version/description/keywords/requires come
# straight from the manifest; maturity/category come from its `colony:` block.
# (interface/pins will be derived from schema.yaml once #1468 lands.)
# Run from the repo root: scripts/build-index.sh
set -euo pipefail
cd "$(dirname "$0")/.."

python3 - <<'PY'
import glob, os, sys
try:
    import yaml
except ImportError:
    sys.exit("build-index needs PyYAML: pip install pyyaml")

def load(p):
    with open(p) as f:
        return yaml.safe_load(f) or {}

entries = []
for meta in sorted(glob.glob("templates/*/package.yaml") + glob.glob("patterns/*/package.yaml")):
    d = os.path.dirname(meta)
    m = load(meta)
    col = m.get("colony", {}) or {}
    entries.append({
        "path": d,
        "name": m.get("name"),
        "version": m.get("version"),
        "description": (m.get("description") or "").strip() or None,
        "platform_version": m.get("platform_version"),
        "keywords": m.get("keywords"),
        "requires": m.get("requires"),          # explicit, verify-checked audit surface
        "maturity": col.get("maturity"),        # Colony curation
        "category": col.get("category"),        # Colony curation
    })

out = {"version": 1, "entries": entries or []}
with open("index.yaml", "w") as f:
    f.write("# GENERATED by scripts/build-index.sh — do not edit by hand.\n")
    f.write("# Catalog derived from each entry's package.yaml. Regenerate after changes.\n")
    yaml.safe_dump(out, f, sort_keys=False, default_flow_style=False)
print(f"wrote index.yaml ({len(entries)} entries)")
PY
