#!/usr/bin/env bash
# Regenerate index.yaml — the catalog aggregating every entry's metadata.
# This is the surface a future `swarm add <name>` / discovery UI consumes.
# Run from the repo root: scripts/build-index.sh
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=index.yaml
{
  echo "# GENERATED by scripts/build-index.sh — do not edit by hand."
  echo "# Catalog of every Colony entry. Regenerate after adding/changing an entry."
  echo "version: 1"
  echo "entries:"
  shopt -s nullglob
  found=0
  for meta in templates/*/template.yaml patterns/*/pattern.yaml; do
    found=1
    dir="$(dirname "$meta")"
    echo "  - path: $dir"
    # indent the entry metadata under the catalog record
    sed 's/^/    /' "$meta"
  done
  if [ "$found" -eq 0 ]; then
    echo "  [] # no entries yet"
  fi
} > "$OUT"

echo "wrote $OUT"
